# Generated by Django 5.0.14 on 2026-01-24 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gift_type",
                    models.CharField(
                        choices=[
                            ("flower", "花束"),
                            ("heart", "愛心"),
                            ("star", "星星"),
                            ("ring", "戒指"),
                            ("teddy", "泰迪熊"),
                            ("cake", "蛋糕"),
                            ("music", "音樂盒"),
                            ("letter", "情書"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "禮物",
                "verbose_name_plural": "禮物",
                "db_table": "gifts",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("stranger", "陌生人"),
                            ("acquaintance", "認識"),
                            ("friend", "朋友"),
                            ("close_friend", "好友"),
                            ("crush", "曖昧"),
                            ("lover", "戀人"),
                            ("partner", "伴侶"),
                        ],
                        default="stranger",
                        max_length=20,
                    ),
                ),
                ("closeness", models.IntegerField(default=0, help_text="親密度 0-100")),
                ("trust", models.IntegerField(default=50, help_text="信任度 0-100")),
                ("romantic", models.IntegerField(default=0, help_text="浪漫值 0-100")),
                ("interaction_count", models.IntegerField(default=0)),
                (
                    "ai_interaction_count",
                    models.IntegerField(default=0, help_text="與 AI 分身互動次數"),
                ),
                (
                    "real_interaction_count",
                    models.IntegerField(default=0, help_text="真人互動次數"),
                ),
                ("first_met", models.DateTimeField(auto_now_add=True)),
                ("became_friends_at", models.DateTimeField(blank=True, null=True)),
                ("became_lovers_at", models.DateTimeField(blank=True, null=True)),
                ("last_interaction", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, help_text="AI 生成的關係描述")),
                ("shared_memories", models.JSONField(default=list, help_text="共同記憶")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "關係",
                "verbose_name_plural": "關係",
                "db_table": "relationships",
            },
        ),
        migrations.CreateModel(
            name="RelationshipEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("first_chat", "首次對話"),
                            ("stage_up", "關係升級"),
                            ("gift", "送禮物"),
                            ("date", "約會"),
                            ("confession", "告白"),
                            ("anniversary", "紀念日"),
                            ("special", "特殊事件"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "關係事件",
                "verbose_name_plural": "關係事件",
                "db_table": "relationship_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
