# Generated by Django 5.0.14 on 2026-01-24 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "app_name",
                    models.CharField(
                        blank=True, help_text="所屬 App（空白=全域）", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "翻譯分類",
                "verbose_name_plural": "翻譯分類",
                "db_table": "translation_categories",
                "ordering": ["app_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TranslationKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="翻譯鍵（如 btn.submit）", max_length=100),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="說明這個文字用在哪裡", max_length=200
                    ),
                ),
                ("default_text", models.TextField(help_text="預設文字（繁體中文）")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="translations.translationcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "翻譯鍵",
                "verbose_name_plural": "翻譯鍵",
                "db_table": "translation_keys",
                "ordering": ["category", "key"],
                "unique_together": {("category", "key")},
            },
        ),
        migrations.CreateModel(
            name="TranslationValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language",
                    models.CharField(help_text="語言代碼（如 en, ja）", max_length=10),
                ),
                ("text", models.TextField(help_text="翻譯文字")),
                ("is_verified", models.BooleanField(default=False, help_text="是否已校對")),
                (
                    "translator",
                    models.CharField(blank=True, help_text="翻譯者", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "translation_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="translations.translationkey",
                    ),
                ),
            ],
            options={
                "verbose_name": "翻譯內容",
                "verbose_name_plural": "翻譯內容",
                "db_table": "translation_values",
                "unique_together": {("translation_key", "language")},
            },
        ),
    ]
