# Generated by Django 5.0.14 on 2026-01-24 05:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order", models.IntegerField(default=0, help_text="問題順序")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("worldview", "世界觀"),
                            ("lifeview", "人生觀"),
                            ("values", "價值觀"),
                            ("interests", "興趣"),
                            ("personality", "性格"),
                            ("communication", "對話風格"),
                            ("emotional", "情感需求"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "單選"),
                            ("multiple_choice", "多選"),
                            ("scale", "量表"),
                            ("text", "文字"),
                            ("tags", "標籤"),
                        ],
                        default="single_choice",
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField(verbose_name="問題內容")),
                (
                    "allow_multiple",
                    models.BooleanField(default=False, help_text="是否允許多選"),
                ),
                ("max_selections", models.IntegerField(default=1, help_text="最多可選幾個")),
                (
                    "scale_left_label",
                    models.CharField(blank=True, help_text="量表左側標籤", max_length=100),
                ),
                (
                    "scale_right_label",
                    models.CharField(blank=True, help_text="量表右側標籤", max_length=100),
                ),
                (
                    "analysis_field",
                    models.CharField(blank=True, help_text="對應的靈魂檔案欄位", max_length=50),
                ),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "問卷問題",
                "verbose_name_plural": "問卷問題",
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_premium", models.BooleanField(default=False)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶",
                "verbose_name_plural": "用戶",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(help_text="選項值", max_length=50)),
                ("label", models.CharField(help_text="顯示文字", max_length=200)),
                ("order", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="users.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "問題選項",
                "verbose_name_plural": "問題選項",
                "db_table": "question_options",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SoulProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "worldview",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "optimism": 0-100,        # 悲觀←→樂觀\n            "spirituality": 0-100,    # 唯物←→唯心\n            "individualism": 0-100,   # 集體←→個人主義\n            "changeOriented": 0-100   # 傳統←→求變\n        }\n    ',
                    ),
                ),
                (
                    "lifeview",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "purpose": ["追求快樂", "實現自我", "幫助他人", "創造價值"],\n            "priorities": ["家庭", "事業", "自由", "愛情", "健康"],\n            "lifeStage": "探索期" | "奮鬥期" | "穩定期" | "享受期"\n        }\n    ',
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "core": ["誠實", "創意", "勇氣", "善良", "智慧"],\n            "dealbreakers": ["欺騙", "冷漠"],\n            "importanceRank": {\n                "love": 1-5,\n                "friendship": 1-5,\n                "career": 1-5,\n                "freedom": 1-5,\n                "security": 1-5\n            }\n        }\n    ',
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "categories": ["藝術", "科技", "運動", "美食", "旅行", "音樂", "閱讀"],\n            "specific": {\n                "music": ["獨立音樂", "古典", "電子"],\n                "movies": ["文藝片", "科幻", "紀錄片"],\n                "books": ["心理學", "小說", "哲學"],\n                "hobbies": ["攝影", "烹飪", "園藝", "遊戲"]\n            },\n            "depth": "casual" | "enthusiast" | "expert"\n        }\n    ',
                    ),
                ),
                (
                    "personality",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "mbti": "INFP" | "ENTJ" | ...,\n            "traits": {\n                "introversion": 0-100,  # 內向←→外向\n                "intuition": 0-100,     # 感覺←→直覺\n                "thinking": 0-100,      # 情感←→思考\n                "judging": 0-100        # 知覺←→判斷\n            },\n            "socialStyle": "傾聽者" | "分享者" | "引導者"\n        }\n    ',
                    ),
                ),
                (
                    "communication_style",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "humor": 0-100,            # 幽默程度\n            "depth": 0-100,            # 深度 vs 輕鬆\n            "emotionality": 0-100,     # 情感表達程度\n            "preferredTopics": ["人生哲學", "日常趣事", "專業話題"]\n        }\n    ',
                    ),
                ),
                (
                    "emotional_needs",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "companionship": 0-100,    # 陪伴需求\n            "validation": 0-100,       # 被認可需求\n            "stimulation": 0-100,      # 刺激/新鮮感需求\n            "understanding": 0-100     # 被理解需求\n        }\n    ',
                    ),
                ),
                (
                    "love_style",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "attachmentType": "secure" | "anxious" | "avoidant",\n            "loveLanguage": ["肯定的言語", "精心時刻", "禮物", "服務", "肢體接觸"],\n            "romanticLevel": 0-100,\n            "jealousy": 0-100\n        }\n    ',
                    ),
                ),
                (
                    "relationship_behavior",
                    models.JSONField(
                        default=dict,
                        help_text='\n        {\n            "initiativeLevel": 0-100,  # 主動程度\n            "expressiveness": 0-100,   # 表達愛意程度\n            "supportStyle": "傾聽型" | "建議型" | "陪伴型"\n        }\n    ',
                    ),
                ),
                (
                    "soul_vector",
                    models.JSONField(
                        default=list,
                        help_text="Soul embedding vector (1536 dimensions)",
                    ),
                ),
                ("questionnaire_completed", models.BooleanField(default=False)),
                ("analysis_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soul_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "靈魂檔案",
                "verbose_name_plural": "靈魂檔案",
                "db_table": "soul_profiles",
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.JSONField(help_text="回答內容（可以是字串、列表、數字等）")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="users.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "問卷回應",
                "verbose_name_plural": "問卷回應",
                "db_table": "questionnaire_responses",
                "unique_together": {("user", "question")},
            },
        ),
    ]
