# Generated by Django 5.0.14 on 2026-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="placeholder_en",
            field=models.CharField(blank=True, max_length=200, verbose_name="提示文字（英文）"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_en",
            field=models.TextField(blank=True, verbose_name="問題內容（英文）"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_es",
            field=models.TextField(blank=True, verbose_name="問題內容（西班牙文）"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_fr",
            field=models.TextField(blank=True, verbose_name="問題內容（法文）"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_ja",
            field=models.TextField(blank=True, verbose_name="問題內容（日文）"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_ko",
            field=models.TextField(blank=True, verbose_name="問題內容（韓文）"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_zh_hans",
            field=models.TextField(blank=True, verbose_name="問題內容（簡中）"),
        ),
        migrations.AddField(
            model_name="question",
            name="scale_left_label_en",
            field=models.CharField(blank=True, max_length=100, verbose_name="左側標籤（英文）"),
        ),
        migrations.AddField(
            model_name="question",
            name="scale_right_label_en",
            field=models.CharField(blank=True, max_length=100, verbose_name="右側標籤（英文）"),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="label_en",
            field=models.CharField(blank=True, max_length=200, verbose_name="英文"),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="label_es",
            field=models.CharField(blank=True, max_length=200, verbose_name="西班牙文"),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="label_fr",
            field=models.CharField(blank=True, max_length=200, verbose_name="法文"),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="label_ja",
            field=models.CharField(blank=True, max_length=200, verbose_name="日文"),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="label_ko",
            field=models.CharField(blank=True, max_length=200, verbose_name="韓文"),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="label_zh_hans",
            field=models.CharField(blank=True, max_length=200, verbose_name="簡中"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(verbose_name="問題內容（繁中）"),
        ),
        migrations.AlterField(
            model_name="question",
            name="scale_left_label",
            field=models.CharField(blank=True, help_text="量表左側標籤（繁中）", max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="scale_right_label",
            field=models.CharField(blank=True, help_text="量表右側標籤（繁中）", max_length=100),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="label",
            field=models.CharField(help_text="顯示文字（繁中）", max_length=200),
        ),
    ]
