# Generated by Django 5.0.14 on 2026-01-24 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="AI 分身名稱", max_length=100)),
                (
                    "avatar_look",
                    models.CharField(
                        blank=True,
                        help_text="Habbo look code (e.g., hd-180-1.hr-100-61.ch-210-66)",
                        max_length=500,
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="AI 分身自我介紹", max_length=500),
                ),
                (
                    "current_location",
                    models.JSONField(
                        default=dict,
                        help_text='{"x": 0, "y": 0, "z": 0, "room_id": "uuid"}',
                    ),
                ),
                (
                    "current_action",
                    models.CharField(
                        default="idle",
                        help_text="idle | walking | talking | sitting | dancing",
                        max_length=50,
                    ),
                ),
                (
                    "current_emotion",
                    models.CharField(
                        default="neutral",
                        help_text="neutral | happy | sad | excited | thinking",
                        max_length=50,
                    ),
                ),
                (
                    "current_target",
                    models.UUIDField(
                        blank=True, help_text="目前互動對象的 Agent ID", null=True
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                (
                    "is_autonomous",
                    models.BooleanField(default=True, help_text="是否自主行動（用戶可以接管）"),
                ),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("total_conversations", models.IntegerField(default=0)),
                ("total_friends_made", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI 分身",
                "verbose_name_plural": "AI 分身",
                "db_table": "agents",
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("move", "移動"),
                            ("chat", "對話"),
                            ("wave", "打招呼"),
                            ("sit", "坐下"),
                            ("stand", "站起"),
                            ("dance", "跳舞"),
                            ("think", "思考"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_location",
                    models.JSONField(
                        blank=True, help_text='目標位置 {"x": 0, "y": 0}', null=True
                    ),
                ),
                ("parameters", models.JSONField(default=dict, help_text="行動參數")),
                ("priority", models.IntegerField(default=5, help_text="優先級 1-10")),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="pending | executing | completed | cancelled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "行動",
                "verbose_name_plural": "行動",
                "db_table": "agent_actions",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "schedule",
                    models.JSONField(
                        default=list,
                        help_text='\n        [\n            {"hour": 8, "activity": "起床", "location": "bedroom"},\n            {"hour": 9, "activity": "在咖啡廳閒逛", "location": "cafe"},\n            {"hour": 12, "activity": "和朋友聊天", "location": "plaza"},\n            ...\n        ]\n        ',
                    ),
                ),
                ("current_hour_index", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "每日計畫",
                "verbose_name_plural": "每日計畫",
                "db_table": "daily_plans",
            },
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("observation", "觀察"),
                            ("reflection", "反思"),
                            ("plan", "計畫"),
                            ("conversation", "對話"),
                            ("emotion", "情感"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="記憶內容描述")),
                ("importance", models.IntegerField(default=5, help_text="重要性評分 1-10")),
                (
                    "related_agents",
                    models.JSONField(default=list, help_text="相關 Agent IDs"),
                ),
                (
                    "location",
                    models.JSONField(
                        default=dict,
                        help_text='發生地點 {"x": 0, "y": 0, "room_id": "uuid"}',
                    ),
                ),
                (
                    "emotion",
                    models.CharField(blank=True, help_text="當時的情感狀態", max_length=50),
                ),
                (
                    "embedding",
                    models.JSONField(
                        default=list,
                        help_text="Memory embedding vector (1536 dimensions)",
                    ),
                ),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("access_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "記憶",
                "verbose_name_plural": "記憶",
                "db_table": "memories",
                "ordering": ["-created_at"],
            },
        ),
    ]
