# Generated by Django 5.0.14 on 2026-01-24 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="target_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targeted_by_actions",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="dailyplan",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_plans",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="agents.agent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyplan",
            unique_together={("agent", "date")},
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["agent", "type"], name="memories_agent_i_75e8f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["agent", "importance"], name="memories_agent_i_194e54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["agent", "-created_at"], name="memories_agent_i_ffc58f_idx"
            ),
        ),
    ]
