# Generated by Django 5.0.14 on 2026-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="last_chat_message",
            field=models.CharField(
                blank=True, default="", help_text="最近說的話", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_chat_time",
            field=models.DateTimeField(blank=True, help_text="最近說話時間", null=True),
        ),
    ]
