# Generated by Django 5.0.14 on 2026-01-25 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_agent_last_chat_message_agent_last_chat_time"),
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("goal", models.CharField(help_text='目標描述 "認識2個新朋友"', max_length=200)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("make_friend", "認識新朋友"),
                            ("chat_topic", "聊特定話題"),
                            ("explore_room", "探索房間"),
                            ("follow_up", "跟進舊友"),
                            ("rest", "休息"),
                            ("observe", "觀察"),
                            ("socialize", "社交"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target_topic",
                    models.CharField(blank=True, help_text='目標話題 "旅行"', max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待執行"),
                            ("active", "執行中"),
                            ("completed", "已完成"),
                            ("expired", "已過期"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=5, help_text="優先級 1-10")),
                (
                    "steps",
                    models.JSONField(default=list, help_text='["找對象", "打招呼", "交換興趣"]'),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("progress_notes", models.JSONField(default=list, help_text="執行過程記錄")),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intents",
                        to="agents.agent",
                    ),
                ),
                (
                    "target_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_by_intents",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "意圖",
                "verbose_name_plural": "意圖",
                "db_table": "agent_intents",
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "status"],
                        name="agent_inten_agent_i_934fbf_idx",
                    ),
                    models.Index(
                        fields=["agent", "-priority"],
                        name="agent_inten_agent_i_663cbd_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="agent_inten_expires_373c9d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentReflection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField(help_text='摘要 "X和我聊了音樂"')),
                ("insight", models.TextField(help_text='洞察 "她今晚想去咖啡廳"')),
                ("importance", models.IntegerField(default=5, help_text="重要性 1-10")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to="agents.agent",
                    ),
                ),
                (
                    "based_on_memories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="derived_reflections",
                        to="agents.memory",
                    ),
                ),
            ],
            options={
                "verbose_name": "反思",
                "verbose_name_plural": "反思",
                "db_table": "agent_reflections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-created_at"],
                        name="agent_refle_agent_i_f079e5_idx",
                    ),
                    models.Index(
                        fields=["agent", "importance"],
                        name="agent_refle_agent_i_153f56_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InteractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("agent_enter", "進入房間"),
                            ("agent_exit", "離開房間"),
                            ("chat_message", "聊天"),
                            ("proximity", "靠近"),
                            ("invite", "邀請"),
                            ("wave", "打招呼"),
                            ("gift", "送禮"),
                            ("emotion_detect", "情緒偵測"),
                            ("goal_achieved", "達成目標"),
                            ("intent_start", "開始意圖"),
                            ("intent_complete", "完成意圖"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(default=dict, help_text="事件附加資料")),
                ("location_x", models.IntegerField(blank=True, null=True)),
                ("location_y", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_as_actor",
                        to="agents.agent",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_logs",
                        to="world.room",
                    ),
                ),
                (
                    "target_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions_as_target",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "交互日誌",
                "verbose_name_plural": "交互日誌",
                "db_table": "interaction_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "-created_at"],
                        name="interaction_room_id_3dfc8b_idx",
                    ),
                    models.Index(
                        fields=["agent", "-created_at"],
                        name="interaction_agent_i_822d4f_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="interaction_event_t_902c8c_idx",
                    ),
                ],
            },
        ),
    ]
