# Generated by Django 5.0.14 on 2026-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_generative_agents_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="emotion_baseline",
            field=models.JSONField(default=dict, help_text="情緒基準線，根據性格設定，情緒會慢慢回歸這個值"),
        ),
        migrations.AddField(
            model_name="agent",
            name="emotion_state",
            field=models.JSONField(
                default=dict,
                help_text='{\n            "happiness": 50,    # 0=難過 ↔ 100=開心\n            "energy": 50,       # 0=疲憊 ↔ 100=有活力\n            "stress": 30,       # 0=平靜 ↔ 100=緊張\n            "openness": 50      # 0=封閉 ↔ 100=開放\n        }',
            ),
        ),
    ]
