# Generated by Django 5.0.14 on 2026-01-24 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待定"),
                            ("liked", "喜歡"),
                            ("passed", "跳過"),
                            ("blocked", "封鎖"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "配對興趣",
                "verbose_name_plural": "配對興趣",
                "db_table": "match_interests",
            },
        ),
        migrations.CreateModel(
            name="MatchRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒絕"),
                            ("expired", "已過期"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, help_text="請求訊息")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "真人連結請求",
                "verbose_name_plural": "真人連結請求",
                "db_table": "match_requests",
            },
        ),
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_score", models.FloatField(help_text="總匹配度 0-100")),
                ("worldview_score", models.FloatField(default=0, help_text="世界觀匹配度")),
                ("lifeview_score", models.FloatField(default=0, help_text="人生觀匹配度")),
                ("values_score", models.FloatField(default=0, help_text="價值觀匹配度")),
                ("interests_score", models.FloatField(default=0, help_text="興趣匹配度")),
                ("personality_score", models.FloatField(default=0, help_text="性格匹配度")),
                (
                    "communication_score",
                    models.FloatField(default=0, help_text="對話風格匹配度"),
                ),
                ("emotional_score", models.FloatField(default=0, help_text="情感需求匹配度")),
                (
                    "highlights",
                    models.JSONField(
                        default=list, help_text='["都重視自由", "喜歡獨立音樂", "人生觀相近"]'
                    ),
                ),
                ("has_dealbreaker", models.BooleanField(default=False)),
                ("dealbreaker_reason", models.TextField(blank=True)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "配對分數",
                "verbose_name_plural": "配對分數",
                "db_table": "match_scores",
            },
        ),
    ]
