# Generated by Django 5.0.14 on 2026-01-24 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField(blank=True, help_text="對話摘要")),
                ("key_topics", models.JSONField(default=list, help_text="關鍵話題")),
                (
                    "shared_interests",
                    models.JSONField(default=list, help_text="發現的共同興趣"),
                ),
                (
                    "emotional_trajectory",
                    models.JSONField(default=list, help_text="情感變化軌跡"),
                ),
                (
                    "recent_messages_json",
                    models.JSONField(default=list, help_text="最近 20 條訊息"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "對話上下文",
                "verbose_name_plural": "對話上下文",
                "db_table": "chat_contexts",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("user", "用戶"), ("agent", "AI 分身")], max_length=10
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文字"),
                            ("image", "圖片"),
                            ("gift", "禮物"),
                            ("system", "系統通知"),
                            ("action", "動作"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="附加資料 (圖片URL, 禮物類型等)"),
                ),
                (
                    "emotion",
                    models.CharField(blank=True, help_text="訊息帶有的情感", max_length=50),
                ),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "訊息",
                "verbose_name_plural": "訊息",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("user_to_agent", "用戶對AI"),
                            ("agent_to_agent", "AI對AI"),
                            ("user_to_user", "真人對話"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("unread_count", models.IntegerField(default=0)),
                ("message_count", models.IntegerField(default=0)),
                ("last_message_preview", models.CharField(blank=True, max_length=200)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_participant",
                        to="agents.agent",
                    ),
                ),
                (
                    "other_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_other",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "對話",
                "verbose_name_plural": "對話",
                "db_table": "conversations",
                "ordering": ["-last_message_at"],
            },
        ),
    ]
