# Generated by Django 5.0.14 on 2026-01-25 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="mode",
            field=models.CharField(
                choices=[("ai", "AI 代聊"), ("user", "用戶親自"), ("paused", "暫停")],
                default="ai",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="mode_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ConversationSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateTimeField(help_text="摘要涵蓋的開始時間")),
                ("period_end", models.DateTimeField(help_text="摘要涵蓋的結束時間")),
                ("message_count", models.IntegerField(default=0, help_text="此期間的訊息數")),
                ("summary_text", models.TextField(help_text="AI 生成的對話摘要")),
                ("key_topics", models.JSONField(default=list, help_text="關鍵話題列表")),
                (
                    "emotional_tone",
                    models.CharField(blank=True, help_text="情感基調", max_length=50),
                ),
                ("best_moment", models.TextField(blank=True, help_text="最佳時刻/亮點")),
                (
                    "shared_interests_found",
                    models.JSONField(default=list, help_text="發現的共同興趣"),
                ),
                (
                    "impression_score",
                    models.IntegerField(default=50, help_text="當前印象分 (0-100)"),
                ),
                (
                    "impression_delta",
                    models.IntegerField(default=0, help_text="印象分變化 (-10 to +10)"),
                ),
                (
                    "compatibility_trend",
                    models.CharField(
                        choices=[("up", "上升"), ("down", "下降"), ("neutral", "持平")],
                        default="neutral",
                        help_text="配對趨勢",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False, help_text="用戶是否已讀")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "對話摘要",
                "verbose_name_plural": "對話摘要",
                "db_table": "conversation_summaries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "-created_at"],
                        name="conversatio_convers_1eefbd_idx",
                    ),
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="conversatio_is_read_7f3699_idx",
                    ),
                ],
            },
        ),
    ]
