# Generated by Django 5.0.14 on 2026-01-24 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("public", "公共區域"),
                            ("cafe", "咖啡廳"),
                            ("plaza", "廣場"),
                            ("park", "公園"),
                            ("bar", "酒吧"),
                            ("library", "圖書館"),
                            ("gym", "健身房"),
                            ("private", "私人房間"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("width", models.IntegerField(default=20)),
                ("height", models.IntegerField(default=20)),
                (
                    "floor_plan",
                    models.JSONField(
                        default=list, help_text="2D array of walkable tiles"
                    ),
                ),
                (
                    "spawn_points",
                    models.JSONField(default=list, help_text='[{"x": 5, "y": 5}, ...]'),
                ),
                (
                    "furniture",
                    models.JSONField(
                        default=list,
                        help_text='\n        [\n            {"type": "sofa", "x": 3, "y": 4, "rotation": 2},\n            {"type": "table", "x": 5, "y": 5, "rotation": 0},\n            ...\n        ]\n        ',
                    ),
                ),
                ("max_capacity", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("visit_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "房間",
                "verbose_name_plural": "房間",
                "db_table": "rooms",
            },
        ),
        migrations.CreateModel(
            name="AgentPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x", models.IntegerField(default=0)),
                ("y", models.IntegerField(default=0)),
                ("z", models.IntegerField(default=0, help_text="樓層/高度")),
                ("direction", models.IntegerField(default=2, help_text="面向方向 0-7")),
                ("is_sitting", models.BooleanField(default=False)),
                ("is_moving", models.BooleanField(default=False)),
                ("target_x", models.IntegerField(blank=True, null=True)),
                ("target_y", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position",
                        to="agents.agent",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_positions",
                        to="world.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 位置",
                "verbose_name_plural": "Agent 位置",
                "db_table": "agent_positions",
            },
        ),
        migrations.CreateModel(
            name="WorldEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("agent_enter", "Agent 進入房間"),
                            ("agent_leave", "Agent 離開房間"),
                            ("agent_chat", "Agent 對話"),
                            ("agent_action", "Agent 動作"),
                            ("room_announcement", "房間公告"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("x", models.IntegerField(blank=True, null=True)),
                ("y", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="world_events",
                        to="agents.agent",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="world.room",
                    ),
                ),
                (
                    "target_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_world_events",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "世界事件",
                "verbose_name_plural": "世界事件",
                "db_table": "world_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "-created_at"],
                        name="world_event_room_id_801cd1_idx",
                    )
                ],
            },
        ),
    ]
